version: '3.8'
services:
  public-api:
    container_name: subscriptions-public-api-svc
    build:
      context: ./public-api
      dockerfile: Dockerfile
    image: davidcki/subscriptions-public-api
    ports:
      - 10010:10010
    links:
      - subscriptions
    environment:
      - subscriptions.service.url=http://subscriptions:10011
  subscriptions:
    container_name: subscriptions-svc
    build:
      context: ./subscriptions
      dockerfile: Dockerfile
    image: davidcki/subscriptions
    links:
      - mongo
      - rabbitmq
  email:
    container_name: subscriptions-email-svc
    build:
      context: ./email
      dockerfile: Dockerfile
    image: davidcki/subscriptions-email
    ports:
      - 10012:10012
  mongo:
    container_name: subscriptions-mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=subscriptions
      - MONGO_INITDB_ROOT_PASSWORD=subspassword
    volumes:
      - ./mongo-volume:/data/db
  rabbitmq:
    container_name: subscriptions-rabbitmq
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  mongo-volume: